### ISSUE TITLE
Error in Config

### ISSUE THREAD

**Issue by camjac251** [Arcanemagus/plexWatchWeb#4] opened 2015-05-30 02:04 UTC
I like what you did with Plexwatchweb but noticed something that was off. For the date format, when installing it was set to m/D/YYYY, I changed mine to M/D/YYYY and it was fine.

**Comment by Arcanemagus** [comment] 2015-05-30 22:21
I'll look into that, it looks like at one point they switched from using D3.js for date formatting to Moment.js, and may not have fixed all the points where that affected things. My Code Cleanup branch (which I'm assuming you are talking about) was intended to bring the codebase to a useable state for further fixes to be based off of.

**Comment by Arcanemagus** [comment] 2015-05-30 22:30
Good catch, the placeholder was correct ('M/D/YYYY') but the default value if unset was 'm/D/YYYY'. Fixed in 54bf785.

**Closed as completed** 2015-05-30 22:32 UTC
